services:
  - type: web
    name: biblioteca-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn biblioteca.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: biblioteca-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.8
    autoDeploy: true

databases:
  - name: biblioteca-db
    databaseName: biblioteca
    ipAllowList: [] 